/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as TableTableIdRouteImport } from './routes/table.$tableId'
import { Route as PublicReservationsRouteImport } from './routes/_public.reservations'
import { Route as PublicMenuRouteImport } from './routes/_public.menu'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicExperienceRouteImport } from './routes/_public.experience'
import { Route as PublicContactRouteImport } from './routes/_public.contact'

const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const TableTableIdRoute = TableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicReservationsRoute = PublicReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMenuRoute = PublicMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicExperienceRoute = PublicExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/reception': typeof ReceptionRoute
  '/contact': typeof PublicContactRoute
  '/experience': typeof PublicExperienceRoute
  '/gallery': typeof PublicGalleryRoute
  '/menu': typeof PublicMenuRoute
  '/reservations': typeof PublicReservationsRoute
  '/table/$tableId': typeof TableTableIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/reception': typeof ReceptionRoute
  '/contact': typeof PublicContactRoute
  '/experience': typeof PublicExperienceRoute
  '/gallery': typeof PublicGalleryRoute
  '/menu': typeof PublicMenuRoute
  '/reservations': typeof PublicReservationsRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRoute
  '/reception': typeof ReceptionRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/experience': typeof PublicExperienceRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/menu': typeof PublicMenuRoute
  '/_public/reservations': typeof PublicReservationsRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reception'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/reservations'
    | '/table/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/reception'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/menu'
    | '/reservations'
    | '/table/$tableId'
    | '/'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/reception'
    | '/_public/contact'
    | '/_public/experience'
    | '/_public/gallery'
    | '/_public/menu'
    | '/_public/reservations'
    | '/table/$tableId'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRoute
  ReceptionRoute: typeof ReceptionRoute
  TableTableIdRoute: typeof TableTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/reservations': {
      id: '/_public/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof PublicReservationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/menu': {
      id: '/_public/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PublicMenuRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/experience': {
      id: '/_public/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof PublicExperienceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicExperienceRoute: typeof PublicExperienceRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicMenuRoute: typeof PublicMenuRoute
  PublicReservationsRoute: typeof PublicReservationsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicExperienceRoute: PublicExperienceRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicMenuRoute: PublicMenuRoute,
  PublicReservationsRoute: PublicReservationsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRoute,
  ReceptionRoute: ReceptionRoute,
  TableTableIdRoute: TableTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
